# Data Loading and Initial Inspection

This notebook loads the BASt traffic dataset and examines the raw structure before any analysis begins. The goals are to confirm the file format, inspect the available columns, understand data quality, and prepare the data for the cleaning stage.

### Step 1: Load the raw dataset
This section imports the traffic data and inspects the initial structure before cleaning.

In [1]:
# Load and inspect the raw traffic data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("ggplot")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.max_colwidth", None)

In [ ]:
# Load and inspect the raw traffic data
# AI-assisted: Debugging suggestion from ChatGPT over the encoding issue in reading the CSV file
encodings = ["utf-8", "cp1252", "latin1", "iso-8859-1"]

for enc in encodings:
    try:
        df = pd.read_csv(
            "../data/Zeitreihe.csv",
            sep=";",
            encoding=enc,
            nrows=5
        )
        print(f"SUCCESS: {enc}")
        break
    except Exception as e:
        print(f"FAILED: {enc} -> {e}")

FAILED: utf-8 -> 'utf-8' codec can't decode byte 0xfc in position 7: invalid start byte
SUCCESS: cp1252

In [12]:
# Load and inspect the raw traffic data
file_path = "../data/Zeitreihe.csv"

df = pd.read_csv(
    file_path,
    sep=";",
    encoding="cp1252",
    low_memory=False
)

In [13]:
# Load and inspect the raw traffic data
print("Shape of Dataset")
print(df.shape)

print("\n")

print("First Five Rows")
display(df.head())

Shape of Dataset
(34451, 256)


First Five Rows

,Jahr,TK_Nr,DZ_Nr,DZ_Name,Land_Nr,Land_Code,Str_Kl,Str_Nr,Str_Zus,Erf_Art,Fernziel_Ri1,Nahziel_Ri1,Hi_Ri1,Fernziel_Ri2,Nahziel_Ri2,Hi_Ri2,Anz_Fs_Q,Betriebs_km,vT_MobisSo,vT_W,vT_U,vT_S,DTV_Kfz_MobisSo_Q,DTV_Kfz_MobisSo_Ri1,DTV_Kfz_MobisSo_Ri2,DTV_Kfz_W_Q,DTV_Kfz_W_Ri1,DTV_Kfz_W_Ri2,DTV_Kfz_U_Q,DTV_Kfz_U_Ri1,DTV_Kfz_U_Ri2,DTV_Kfz_S_Q,DTV_Kfz_S_Ri1,DTV_Kfz_S_Ri2,Entw_Kfz_MobisSo_Q,Entw_Kfz_W_Q,Entw_Kfz_U_Q,Entw_Kfz_S_Q,DTV_SV_MobisSo_Q,DTV_SV_MobisSo_Ri1,DTV_SV_MobisSo_Ri2,DTV_SV_W_Q,DTV_SV_W_Ri1,DTV_SV_W_Ri2,DTV_SV_U_Q,DTV_SV_U_Ri1,DTV_SV_U_Ri2,DTV_SV_S_Q,DTV_SV_S_Ri1,DTV_SV_S_Ri2,Entw_SV_MobisSo_Q,Entw_SV_W_Q,Entw_SV_U_Q,Entw_SV_S_Q,pSV_MobisSo_Q,pSV_W_Q,pSV_U_Q,pSV_S_Q,fer,bSo,bFr,Mt,pMt,Mn,pMn,Md,pMd,Me,pMe,MSV30_Kfz_MobisSo_Q,MSV30_Kfz_W_Q,MSV30_Kfz_U_Q,MSV30_Kfz_S_Q,MSV30maxRi_Kfz_MobisSo,MSV30maxRi_Kfz_W,MSV30maxRi_Kfz_U,MSV30maxRi_Kfz_S,pMSV30maxRi_Kfz_MobisSo,pMSV30maxRi_Kfz_W,pMSV30maxRi_Kfz_U,pMSV30maxRi_Kfz_S,Ri_MSV30maxRi_Kfz_MobisSo,Ri_MSV30maxRi_Kfz_W,Ri_MSV30maxRi_Kfz_U,Ri_MSV30maxRi_Kfz_S,DL_Q,DL_Ri1,DL_Ri2,JG,WG_Ri1,WG_Ri2,TG_Mo_Ri1,TGMax1_Mo_Ri1,TGMax2_Mo_Ri1,TG_Mo_Ri2,TGMax1_Mo_Ri2,TGMax2_Mo_Ri2,TG_DiMiDo_Ri1,TGMax1_DiMiDo_Ri1,TGMax2_DiMiDo_Ri1,TG_DiMiDo_Ri2,TGMax1_DiMiDo_Ri2,TGMax2_DiMiDo_Ri2,TG_Fr_Ri1,TGMax1_Fr_Ri1,TGMax2_Fr_Ri1,TG_Fr_Ri2,TGMax1_Fr_Ri2,TGMax2_Fr_Ri2,TG_Sa_Ri1,TGMax1_Sa_Ri1,TGMax2_Sa_Ri1,TG_Sa_Ri2,TGMax1_Sa_Ri2,TGMax2_Sa_Ri2,TG_SoFei_Ri1,TGMax1_SoFei_Ri1,TGMax2_SoFei_Ri1,TG_SoFei_Ri2,TGMax1_SoFei_Ri2,TGMax2_SoFei_Ri2,pPLZ_MobisSo_Q,pLfw_MobisSo_Q,pMot_MobisSo_Q,pPmA_MobisSo_Q,pLoA_MobisSo_Q,pLzg_MobisSo_Q,pSat_MobisSo_Q,pBus_MobisSo_Q,pSon_MobisSo_Q,pPLZ_W_Q,pLfw_W_Q,pMot_W_Q,pPmA_W_Q,pLoA_W_Q,pLzg_W_Q,pSat_W_Q,pBus_W_Q,pSon_W_Q,pPLZ_U_Q,pLfw_U_Q,pMot_U_Q,pPmA_U_Q,pLoA_U_Q,pLzg_U_Q,pSat_U_Q,pBus_U_Q,pSon_U_Q,pPLZ_S_Q,pLfw_S_Q,pMot_S_Q,pPmA_S_Q,pLoA_S_Q,pLzg_S_Q,pSat_S_Q,pBus_S_Q,pSon_S_Q,Koor_UTM32_E,Koor_UTM32_N,DTV_Kfz_WU_MobisFr_Q,DTV_Kfz_WU_MobisFr_Ri1,DTV_Kfz_WU_MobisFr_Ri2,DTV_SV_WU_MobisFr_Q,DTV_SV_WU_MobisFr_Ri1,DTV_SV_WU_MobisFr_Ri2,DTV_Kfz_WU_Sa_Q,DTV_Kfz_WU_Sa_Ri1,DTV_Kfz_WU_Sa_Ri2,DTV_SV_WU_Sa_Q,DTV_SV_WU_Sa_Ri1,DTV_SV_WU_Sa_Ri2,MSV30_Kfz_MobisSo_Ri1,MSV30_Kfz_MobisSo_Ri2,MSV30_Kfz_W_Ri1,MSV30_Kfz_W_Ri2,MSV30_Kfz_U_Ri1,MSV30_Kfz_U_Ri2,MSV30_Kfz_S_Ri1,MSV30_Kfz_S_Ri2,bSV30_MobisSo_Ri1,bSV30_MobisSo_Ri2,bSV30_W_Ri1,bSV30_W_Ri2,bSV30_U_Ri1,bSV30_U_Ri2,bSV30_S_Ri1,bSV30_S_Ri2,DTV_Kfz_W_MobisFr_Q,DTV_Kfz_W_MobisFr_Ri1,DTV_Kfz_W_MobisFr_Ri2,DTV_SV_W_MobisFr_Q,DTV_SV_W_MobisFr_Ri1,DTV_SV_W_MobisFr_Ri2,pSV_W_MobisFr_Q,pSV_W_MobisFr_Ri1,pSV_W_MobisFr_Ri2,Koor_WGS84_N,Koor_WGS84_E,MSV50_Kfz_MobisSo_Ri1,MSV50_Kfz_MobisSo_Ri2,pMSV50_Kfz_MobisSo_Ri1,pMSV50_Kfz_MobisSo_Ri2,bSV50_MobisSo_Ri1,bSV50_MobisSo_Ri2,bLkwK50_MobisSo_Ri1,bLkwK50_MobisSo_Ri2,pMSV50_Kfz_W_MobisFr_Ri1,pMSV50_Kfz_W_MobisFr_Ri2,DTV_Kfz_NZB_DiMiDo_Ri1,DTV_Kfz_NZB_DiMiDo_Ri2,bSo_Ri1,bSo_Ri2,bMo_Ri1,bMo_Ri2,bFr_Ri1,bFr_Ri2,bSa_Ri1,bSa_Ri2,Q_P_D,Q_L1_D,Q_L2_D,Q_K_D,Q_P_E,Q_L1_E,Q_L2_E,Q_K_E,Q_P_N,Q_L1_N,Q_L2_N,Q_K_N,Geo_Sequ,Abschnitt_Ast,Station,Ausrichtung,Maut_SID_Ri1,Maut_SID_Ri2,Anz_Fs_Ri1,Anz_Fs_Ri2,DTA_SV_Ri1,fA_SV_Ri1,qBm_SV_Ri1,B_anno_SV_Ri1,DTA_SV_Ri2,fA_SV_Ri2,qBm_SV_Ri2,B_anno_SV_Ri2,DTV_Bus_Ri1,DTV_LoA_Ri1,DTV_Lzg_Ri1,DTV_Sat_Ri1,DTV_Bus_Ri2,DTV_LoA_Ri2,DTV_Lzg_Ri2,DTV_Sat_Ri2,Anmerkungen,Unnamed: 255
0,2023,2426,2218,AD HH-Südost (O),2,HH,A,1,NaN,2,Lübeck,AS Hamburg-Südost,N,Hamburg,AD Dreieck Hamburg-Südost (A25),S,6,"149,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,572.102,5.929.284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"53,50754848","10,08718293",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530,2426012O2426019O,"0,397",Ri1_ist_VonNK,2.533,1.034,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netzmodernisierung in 2023,NaN
1,2023,2426,2217,AD HH-Südost (W),2,HH,A,1,NaN,8+1,Lübeck,AD Dreieck Hamburg-Südost (A25),N,Hamburg,AK Kreuz Hamburg-Süd (A255),S,8,"150,3",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,569.966,5.929.459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"53,50941419","10,05502803",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520,2426019O2426001O,"0,477",Ri1_ist_VonNK,3.952,2.545,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netzmodernisierung in 2023,NaN
2,2023,4908,5675,AK Leverkusen (O),5,NW,A,1,NaN,8+1,Dortmund,AS Burscheid,N,Köln,AK Kreuz Leverkusen (A3),S,6,"402,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.845,5.658.635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,06330659","7,07118583",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260,4908018A4908083A,"5,101",Ri1_ist_NachNK,2.374,907,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenprobleme in 2023,NaN
3,2023,4908,5035,AK Leverkusen (W),5,NW,A,1,NaN,8+1,Dortmund,AK Kreuz Leverkusen (A3),N,Köln,AK Kreuz Leverkusen-West (A59),S,6,"403,7",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358.801,5.655.933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,03757536","6,98603730",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250,4907071A4908018A,"1,613",Ri1_ist_NachNK,3.829,2.388,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenprobleme in 2023,NaN
4,2023,6507,353,AS Eppelborn,10,SL,A,1,NaN,8+1,Köln,AS Tholey,N,Saarbrücken,AS Eppelborn,S,5,"185,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,353.633,5.475.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"49,41525237","6,98198701",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,6507026O6507012O,"5,486",Ri1_ist_VonNK,278,2.197,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baustelle in 2023,NaN

In [17]:
# Load and inspect the raw traffic data
print(df.columns)

Index(['Jahr', 'TK_Nr', 'DZ_Nr', 'DZ_Name', 'Land_Nr', 'Land_Code', 'Str_Kl',
       'Str_Nr', 'Str_Zus', 'Erf_Art',
       ...
       'DTV_Bus_Ri1', 'DTV_LoA_Ri1', 'DTV_Lzg_Ri1', 'DTV_Sat_Ri1',
       'DTV_Bus_Ri2', 'DTV_LoA_Ri2', 'DTV_Lzg_Ri2', 'DTV_Sat_Ri2',
       'Anmerkungen', 'Unnamed: 255'],
      dtype='str', length=256)

In [18]:
# Load and inspect the raw traffic data
print(f"Total columns: {len(df.columns)}")

Total columns: 256

In [19]:
# Load and inspect the raw traffic data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34451 entries, 0 to 34450
Columns: 256 entries, Jahr to Unnamed: 255
dtypes: float64(114), int64(9), str(133)
memory usage: 67.3 MB

In [20]:
# Load and inspect the raw traffic data
df.describe(include="all")

,Jahr,TK_Nr,DZ_Nr,DZ_Name,Land_Nr,Land_Code,Str_Kl,Str_Nr,Str_Zus,Erf_Art,Fernziel_Ri1,Nahziel_Ri1,Hi_Ri1,Fernziel_Ri2,Nahziel_Ri2,Hi_Ri2,Anz_Fs_Q,Betriebs_km,vT_MobisSo,vT_W,vT_U,vT_S,DTV_Kfz_MobisSo_Q,DTV_Kfz_MobisSo_Ri1,DTV_Kfz_MobisSo_Ri2,DTV_Kfz_W_Q,DTV_Kfz_W_Ri1,DTV_Kfz_W_Ri2,DTV_Kfz_U_Q,DTV_Kfz_U_Ri1,DTV_Kfz_U_Ri2,DTV_Kfz_S_Q,DTV_Kfz_S_Ri1,DTV_Kfz_S_Ri2,Entw_Kfz_MobisSo_Q,Entw_Kfz_W_Q,Entw_Kfz_U_Q,Entw_Kfz_S_Q,DTV_SV_MobisSo_Q,DTV_SV_MobisSo_Ri1,DTV_SV_MobisSo_Ri2,DTV_SV_W_Q,DTV_SV_W_Ri1,DTV_SV_W_Ri2,DTV_SV_U_Q,DTV_SV_U_Ri1,DTV_SV_U_Ri2,DTV_SV_S_Q,DTV_SV_S_Ri1,DTV_SV_S_Ri2,Entw_SV_MobisSo_Q,Entw_SV_W_Q,Entw_SV_U_Q,Entw_SV_S_Q,pSV_MobisSo_Q,pSV_W_Q,pSV_U_Q,pSV_S_Q,fer,bSo,bFr,Mt,pMt,Mn,pMn,Md,pMd,Me,pMe,MSV30_Kfz_MobisSo_Q,MSV30_Kfz_W_Q,MSV30_Kfz_U_Q,MSV30_Kfz_S_Q,MSV30maxRi_Kfz_MobisSo,MSV30maxRi_Kfz_W,MSV30maxRi_Kfz_U,MSV30maxRi_Kfz_S,pMSV30maxRi_Kfz_MobisSo,pMSV30maxRi_Kfz_W,pMSV30maxRi_Kfz_U,pMSV30maxRi_Kfz_S,Ri_MSV30maxRi_Kfz_MobisSo,Ri_MSV30maxRi_Kfz_W,Ri_MSV30maxRi_Kfz_U,Ri_MSV30maxRi_Kfz_S,DL_Q,DL_Ri1,DL_Ri2,JG,WG_Ri1,WG_Ri2,TG_Mo_Ri1,TGMax1_Mo_Ri1,TGMax2_Mo_Ri1,TG_Mo_Ri2,TGMax1_Mo_Ri2,TGMax2_Mo_Ri2,TG_DiMiDo_Ri1,TGMax1_DiMiDo_Ri1,TGMax2_DiMiDo_Ri1,TG_DiMiDo_Ri2,TGMax1_DiMiDo_Ri2,TGMax2_DiMiDo_Ri2,TG_Fr_Ri1,TGMax1_Fr_Ri1,TGMax2_Fr_Ri1,TG_Fr_Ri2,TGMax1_Fr_Ri2,TGMax2_Fr_Ri2,TG_Sa_Ri1,TGMax1_Sa_Ri1,TGMax2_Sa_Ri1,TG_Sa_Ri2,TGMax1_Sa_Ri2,TGMax2_Sa_Ri2,TG_SoFei_Ri1,TGMax1_SoFei_Ri1,TGMax2_SoFei_Ri1,TG_SoFei_Ri2,TGMax1_SoFei_Ri2,TGMax2_SoFei_Ri2,pPLZ_MobisSo_Q,pLfw_MobisSo_Q,pMot_MobisSo_Q,pPmA_MobisSo_Q,pLoA_MobisSo_Q,pLzg_MobisSo_Q,pSat_MobisSo_Q,pBus_MobisSo_Q,pSon_MobisSo_Q,pPLZ_W_Q,pLfw_W_Q,pMot_W_Q,pPmA_W_Q,pLoA_W_Q,pLzg_W_Q,pSat_W_Q,pBus_W_Q,pSon_W_Q,pPLZ_U_Q,pLfw_U_Q,pMot_U_Q,pPmA_U_Q,pLoA_U_Q,pLzg_U_Q,pSat_U_Q,pBus_U_Q,pSon_U_Q,pPLZ_S_Q,pLfw_S_Q,pMot_S_Q,pPmA_S_Q,pLoA_S_Q,pLzg_S_Q,pSat_S_Q,pBus_S_Q,pSon_S_Q,Koor_UTM32_E,Koor_UTM32_N,DTV_Kfz_WU_MobisFr_Q,DTV_Kfz_WU_MobisFr_Ri1,DTV_Kfz_WU_MobisFr_Ri2,DTV_SV_WU_MobisFr_Q,DTV_SV_WU_MobisFr_Ri1,DTV_SV_WU_MobisFr_Ri2,DTV_Kfz_WU_Sa_Q,DTV_Kfz_WU_Sa_Ri1,DTV_Kfz_WU_Sa_Ri2,DTV_SV_WU_Sa_Q,DTV_SV_WU_Sa_Ri1,DTV_SV_WU_Sa_Ri2,MSV30_Kfz_MobisSo_Ri1,MSV30_Kfz_MobisSo_Ri2,MSV30_Kfz_W_Ri1,MSV30_Kfz_W_Ri2,MSV30_Kfz_U_Ri1,MSV30_Kfz_U_Ri2,MSV30_Kfz_S_Ri1,MSV30_Kfz_S_Ri2,bSV30_MobisSo_Ri1,bSV30_MobisSo_Ri2,bSV30_W_Ri1,bSV30_W_Ri2,bSV30_U_Ri1,bSV30_U_Ri2,bSV30_S_Ri1,bSV30_S_Ri2,DTV_Kfz_W_MobisFr_Q,DTV_Kfz_W_MobisFr_Ri1,DTV_Kfz_W_MobisFr_Ri2,DTV_SV_W_MobisFr_Q,DTV_SV_W_MobisFr_Ri1,DTV_SV_W_MobisFr_Ri2,pSV_W_MobisFr_Q,pSV_W_MobisFr_Ri1,pSV_W_MobisFr_Ri2,Koor_WGS84_N,Koor_WGS84_E,MSV50_Kfz_MobisSo_Ri1,MSV50_Kfz_MobisSo_Ri2,pMSV50_Kfz_MobisSo_Ri1,pMSV50_Kfz_MobisSo_Ri2,bSV50_MobisSo_Ri1,bSV50_MobisSo_Ri2,bLkwK50_MobisSo_Ri1,bLkwK50_MobisSo_Ri2,pMSV50_Kfz_W_MobisFr_Ri1,pMSV50_Kfz_W_MobisFr_Ri2,DTV_Kfz_NZB_DiMiDo_Ri1,DTV_Kfz_NZB_DiMiDo_Ri2,bSo_Ri1,bSo_Ri2,bMo_Ri1,bMo_Ri2,bFr_Ri1,bFr_Ri2,bSa_Ri1,bSa_Ri2,Q_P_D,Q_L1_D,Q_L2_D,Q_K_D,Q_P_E,Q_L1_E,Q_L2_E,Q_K_E,Q_P_N,Q_L1_N,Q_L2_N,Q_K_N,Geo_Sequ,Abschnitt_Ast,Station,Ausrichtung,Maut_SID_Ri1,Maut_SID_Ri2,Anz_Fs_Ri1,Anz_Fs_Ri2,DTA_SV_Ri1,fA_SV_Ri1,qBm_SV_Ri1,B_anno_SV_Ri1,DTA_SV_Ri2,fA_SV_Ri2,qBm_SV_Ri2,B_anno_SV_Ri2,DTV_Bus_Ri1,DTV_LoA_Ri1,DTV_Lzg_Ri1,DTV_Sat_Ri1,DTV_Bus_Ri2,DTV_LoA_Ri2,DTV_Lzg_Ri2,DTV_Sat_Ri2,Anmerkungen,Unnamed: 255
count,34451.000000,34451.000000,34451.000000,34451,34451.000000,34451,34451,34451.000000,335,34451,34451,34451,34451,34451,34451,34451,34451.000000,27404,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,29827.000000,27519,27519,27519,27519,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,29085.000000,26605,26605,26605,26605,29085,29085,29085,29085,29827,29827,29827,29827.000000,29087,29827.000000,29087,29827.000000,29087,29827.000000,29087,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999,13999,13999,13999,13999,13999,13999,13999,13999,29827,29827,29827,29827,29827,29825,25615.000000,8237.000000,29825,25304.000000,7625.000000,29827,24916.000000,8572.000000,29826,24635.000000,8562.000000,29827,25339.000000,6257.000000,29826,25666.000000,6891.000000,29827,24485.000000,4735.000000,29826,25175.000000,5207.000000,29824,27512.000000,0.0,29824,27016.000000,0.0,27767,26036,26004,27750,27767,27767,26004,27750,27750,27767,26036,26004,27750,27767,27767,26004,27750,27750,27767,26036,26004,27750,27767,27767,26004,27750,27750,27767,26036,26004,27750,27767,27767,26004,27750,27750,34451.000000,34451,29827.000000,29827.000000,29827.000000,29085.000000,29085.000000,29085.000000,29827.000000,29827.000000,29827.000000,29085.000000,29085.000000,29085.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13999.000000,13855,13855,13855,13855,13855,13855,13855,13855,29827.000000,29827.000000,29827.000000,29085.000000,29085.000000,29085.000000,29085,29082,29082,34451,34451,15828.000000,15828.000000,15828,15828,15227,15227,14807,14807,15828,15828,29827.000000,29827.000000,29827,29827,29827,29827,29827,29827,29827,29827,12862.000000,13265.000000,13265.000000,12862.000000,12862.000000,13265.000000,13265.000000,12862.000000,12862.000000,13265.000000,13265.000000,12862.000000,34451.000000,14072,14072,14072,26618,26618,34451.000000,34451.000000,27715.000000,27715,27715,27715,27715.000000,27715,27715,27715,27715.000000,27715.000000,27715.000000,26002.000000,27715.000000,27715.000000,27715.000000,26002.000000,13775,0.0
unique,NaN,NaN,NaN,2273,NaN,16,2,NaN,3,6,752,2374,4,788,2367,4,NaN,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,758,730,854,922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,957,946,1115,1295,412,471,405,177,104,149,74,NaN,389,NaN,614,NaN,392,NaN,386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220,153,122,148,2,2,2,2,6,6,6,8,7,7,8,NaN,NaN,8,NaN,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,NaN,9,NaN,NaN,9,NaN,NaN,8,NaN,NaN,8,NaN,NaN,439,172,110,62,118,370,312,38,106,499,178,84,64,125,427,363,46,112,425,173,114,69,123,359,303,39,115,212,178,212,63,73,132,116,30,112,NaN,2548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316,313,334,361,342,353,150,143,NaN,NaN,NaN,NaN,NaN,NaN,493,491,504,2567,2567,NaN,NaN,195,196,296,276,259,240,211,218,NaN,NaN,156,156,81,112,115,100,127,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2127,1678,2,2131,2131,NaN,NaN,NaN,235,33,27375,NaN,241,31,27391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2725,NaN
top,NaN,NaN,NaN,Walldorf,NaN,BY,A,NaN,n,8+1,Köln,Koblenz,N,München,Bundesgrenze (CH),S,NaN,"0,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"+1,0","+1,1","+0,8","+1,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"+2,1","+0,2","+1,2","+0,3","5,8","5,8","5,5","1,1","0,93","0,62","1,05",NaN,"5,4",NaN,"6,3",NaN,"5,8",NaN,"2,4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"11,3","10,2","9,7","11,1",R I,R I,R I,R II,E,D,D,A,B,B,D,NaN,NaN,D,NaN,NaN,D,NaN,NaN,D,NaN,NaN,E,NaN,NaN,E,NaN,NaN,D,NaN,NaN,D,NaN,NaN,D,NaN,NaN,D,NaN,NaN,"93,1","6,8","0,6","1,2","2,9","2,4","1,1","0,2","0,0","92,6","7,3","0,5","1,1","3,4","2,7","1,3","0,2","0,0","92,9","7,1","0,7","1,3","3,1","2,5","1,1","0,2","0,0","97,6","5,0","0,8","0,7","0,4","0,2","0,1","0,2","0,0",NaN,5.608.798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,9","2,0","4,9","6,2","3,3","4,5","0,0","0,0",NaN,NaN,NaN,NaN,NaN,NaN,"6,4","6,8","6,7","53,50754848","10,08718293",NaN,NaN,"11,0","10,6","3,1","2,3","0,0","0,8","10,0","9,9",NaN,NaN,"0,64","0,61","0,97","0,98","1,04","1,04","0,76","0,79",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2228003O2129001O,"0,503",Ri1_ist_NachNK,mautfrei,mautfrei,NaN,NaN,NaN,"4,25","0,32",0,NaN,"4,23","0,32",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenprobleme in 2023,NaN
freq,NaN,NaN,NaN,42,NaN,6530,17907,NaN,188,30687,1135,84,18803,946,174,18803,NaN,387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361,364,301,264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,214,225,187,160,263,239,252,1175,2046,756,2404,NaN,271,NaN,162,NaN,285,NaN,409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,368,452,514,457,7930,8131,7944,7507,6470,9606,9615,10650,10564,11355,8237,NaN,NaN,7625,NaN,NaN,8572,NaN,NaN,8562,NaN,NaN,10203,NaN,NaN,9800,NaN,NaN,9264,NaN,NaN,9484,NaN,NaN,9272,NaN,NaN,10661,NaN,NaN,226,598,2295,2233,1195,332,427,6473,3784,207,562,3025,2532,1060,301,397,6332,3743,249,593,2280,2009,1196,321,424,7030,3773,669,702,1403,1852,3056,2308,3356,6137,4547,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137,159,135,136,134,128,800,725,NaN,NaN,NaN,NaN,NaN,NaN,215,210,223,21,21,NaN,NaN,413,408,152,204,368,439,516,485,NaN,NaN,829,731,3913,3966,2074,2595,1259,1340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,35,9243,105,105,NaN,NaN,NaN,302,5597,5,NaN,295,5755,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384,NaN
mean,2014.081623,5181.481931,5703.719021,NaN,7.895910,NaN,NaN,104.206903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.697309,NaN,288.317129,176.190666,62.566064,49.560398,35.850836,24.989225,25.297722,37.356359,25.163625,25.509815,36.582376,25.139804,25.020193,29.130269,30.201722,30.299503,NaN,NaN,NaN,NaN,190.287787,188.518592,187.244808,171.557809,189.805859,190.054083,186.340202,188.025120,188.078442,182.162468,204.174705,201.139837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224.184674,NaN,263.733943,NaN,223.267720,NaN,219.419661,NaN,174.213413,177.394136,195.301383,227.394100,249.506914,248.780479,245.387614,246.474904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.062854,16.961758,NaN,10.717634,16.990820,NaN,11.798322,17.006066,NaN,11.392896,17.031651,NaN,11.983188,15.508071,NaN,11.764474,15.419678,NaN,13.041005,14.313622,NaN,12.947567,14.277703,NaN,16.083454,NaN,NaN,16.385734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,551.304690,NaN,38.121437,25.224345,25.604791,161.097033,191.030348,192.526383,31.981554,25.657522,26.055620,171.828427,180.642310,178.415004,249.914021,252.128028,249.694672,249.948523,243.148042,245.196077,245.806371,245.811503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.241388,25.358871,26.005164,159.046994,191.487225,192.006957,NaN,NaN,NaN,NaN,NaN,213.320545,210.774967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.198331,25.577775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,226.010421,70.575952,195.159658,13.801664,225.629398,28.156653,110.133358,9.009330,261.598332,19.813796,97.789672,2.327088,127.309802,NaN,NaN,NaN,NaN,NaN,1.850309,1.847000,131.648751,NaN,NaN,NaN,130.268404,NaN,NaN,NaN,55.336937,282.483470,160.487004,156.372414,55.203573,282.086739,161.393820,155.597254,NaN,NaN
std,6.036816,1717.765827,2649.038447,NaN,3.850865,NaN,NaN,148.939183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.623606,NaN,86.881751,53.231155,20.593185,15.213609,45.003660,78.143056,79.859737,43.729295,74.193086,76.839967,44.207329,76.436716,76.676073,46.716278,113.355274,112.108679,NaN,NaN,NaN,NaN,287.558637,252.478634,250.733179,283.690623,258.801449,258.845879,287.437253,252.854186,252.790592,248.222742,261.408827,262.126691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,294.791991,NaN,277.780414,NaN,302.787844,NaN,271.981321,NaN,309.930945,308.048935,316.060422,317.693208,313.381209,310.384846,297.209293,279.698756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.347234,0.769198,NaN,4.249359,0.777382,NaN,4.529395,0.689411,NaN,4.431981,0.711218,NaN,3.997833,1.091838,NaN,4.009541,1.162319,NaN,1.999804,0.931456,NaN,1.987595,1.002153,NaN,2.017159,NaN,NaN,1.949627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.517562,NaN,42.460300,72.174733,74.991075,279.910212,263.778620,265.577445,45.004548,89.099876,92.489212,229.951072,247.770554,243.824460,309.678644,309.503802,306.577919,305.176189,291.981001,291.331683,275.312432,275.364023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.844684,72.374128,76.780593,279.037150,265.140237,265.817959,NaN,NaN,NaN,NaN,NaN,298.124682,294.396623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.006944,73.252482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297.659556,65.597511,217.198111,14.682809,274.187173,32.308670,144.607953,11.731553,251.290120,22.558646,135.226237,4.332525,175.411362,NaN,NaN,NaN,NaN,NaN,0.822736,0.821138,258.155403,NaN,NaN,NaN,256.799205,NaN,NaN,NaN,66.266864,284.511241,230.050280,230.926045,65.412943,284.587818,231.422551,230.055681,NaN,NaN
min,2003.000000,1119.000000,101.000000,NaN,1.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,0.000000,0.000000,0.000000,0.000000,1.001000,1.001000,1.000000,1.002000,1.000000,1.002000,1.006000,1.000000,1.000000,1.000000,1.000000,1.001000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,13.000000,NaN,3.000000,13.000000,NaN,6.000000,13.000000,NaN,6.000000,13.000000,NaN,6.000000,13.000000,NaN,6.000000,13.000000,NaN,9.000000,13.000000,NaN,9.000000,13.000000,NaN,10.000000,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283.292000,NaN,1.008000,1.000000,1.000000,0.000000,0.000000,0.000000,1.001000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.008000,1.000000,1.001000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.002000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,10.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,2009.000000,4040.000000,3707.000000,NaN,5.000000,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,256.000000,156.000000,56.000000,43.000000,9.483000,4.886000,4.863500,10.150000,5.226500,5.191000,9.718000,5.015500,4.947000,6.589500,3.453500,3.527000,NaN,NaN,NaN,NaN,3.945000,3.437000,3.445000,3.557000,3.654000,3.675000,3.891000,3.455000,3.470000,3.075000,24.000000,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.513000,NaN,53.000000,NaN,2.558000,NaN,2.374000,NaN,2.101000,2.177500,2.360500,2.619500,2.645000,2.615500,2.537000,2.422000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,8.000000,15.000000,NaN,8.000000,15.000000,NaN,11.000000,14.000000,NaN,11.000000,14.000000,NaN,15.000000,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,423.445000,NaN,10.414000,5.337000,5.303000,3.321000,3.732000,3.782000,8.149500,4.255000,4.216500,3.800000,3.381000,3.189000,2.625500,2.600000,2.593500,2.533000,2.499000,2.449000,2.359000,2.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.469500,5.381000,5.350000,3.291000,3.766000,3.806000,NaN,NaN,NaN,NaN,NaN,2.416000,2.387000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.430000,5.386500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.295000,19.000000,23.000000,5.000000,2.147250,4.000000,6.000000,3.000000,62.000000,3.000000,5.000000,0.000000,20.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,3.162000,NaN,NaN,NaN,3.116500,NaN,NaN,NaN,15.000000,63.000000,3.465500,3.266000,15.000000,62.000000,3.472500,3.316000,NaN,NaN
50%,2015.000000,5208.000000,5340.000000,NaN,7.000000,NaN,NaN,49.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,323.000000,197.000000,71.000000,56.000000,22.924000,11.974000,12.018000,24.269000,12.603000,12.569000,23.516000,12.336000,12.157000,17.296000,9.205000,9.681000,NaN,NaN,NaN,NaN,10.684000,9.465000,9.294000,10.936000,8.948000,8.981000,10.658000,9.114000,9.123000,75.000000,72.000000,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.134000,NaN,135.000000,NaN,4.995000,NaN,89.000000,NaN,5.137000,5.175000,5.278000,5.463000,5.004000,5.239000,5.401000,171.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,8.000000,17.000000,NaN,13.000000,15.000000,NaN,11.000000,15.000000,NaN,13.000000,14.000000,NaN,12.000000,14.000000,NaN,16.000000,NaN,NaN,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,539.468000,NaN,24.971000,12.912000,12.900000,10.610000,8.900000,9.050000,19.909000,10.662000,10.379000,73.000000,80.000000,80.000000,5.088000,5.203000,5.417000,5.505000,5.632000,6.008000,180.000000,178.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.088000,12.942000,12.970000,10.615000,8.985000,9.113000,NaN,NaN,NaN,NaN,NaN,4.082000,4.057000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.912000,12.941000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.821000,47.000000,95.000000,9.000000,116.000000,14.000000,36.000000,5.000000,160.000000,10.000000,28.000000,1.000000,50.000000,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,12.032000,NaN,NaN,NaN,12.123000,NaN,NaN,NaN,31.000000,167.000000,51.000000,51.000000,31.000000,165.000000,51.000000,50.000000,NaN,NaN
75%,2019.000000,6438.000000,8040.000000,NaN,9.000000,NaN,NaN,104.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,351.000000,214.000000,77.000000,60.000000,53.185500,27.139000,27.181500,55.426000,28.352000,28.257500,54.652000,28.083000,27.708000,42.652000,22.119500,22.894000,NaN,NaN,NaN,NaN,356.000000,322.000000,321.000000,288.000000,338.000000,342.000000,345.000000,326.000000,326.000000,232.000000,312.000000,301.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,444.000000,NaN,452.000000,NaN,452.000000,NaN,383.000000,NaN,224.000000,303.500000,402.500000,494.000000,507.000000,495.000000,476.000000,436.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.000000,17.000000,NaN,17.000000,17.000000,NaN,17.000000,17.000000,NaN,17.000000,17.000000,NaN,16.000000,16.000000,NaN,16.000000,16.000000,NaN,15.000000,15.000000,NaN,15.000000,15.000000,NaN,18.000000,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,677.272000,NaN,57.039500,29.061500,29.028000,217.000000,349.000000,353.000000,46.357500,24.309500,23.698000,263.000000,228.000000,228.000000,501.000000,501.000000,491.500000,485.000000,463.000000,466.000000,425.000000,429.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.140500,29.175000,29.169500,204.000000,352.000000,354.000000,NaN,NaN,NaN,NaN,NaN,432.000000,427.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.423500,29.257500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,444.000000,106.000000,321.000000,17.000000,380.000000,43.000000,169.000000,11.000000,412.000000,30.000000,144.000000,3.000000,150.000000,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,32.358500,NaN,NaN,NaN,32.208000,NaN,NaN,NaN,72.000000,469.000000,223.000000,197.750000,72.000000,464.000000,226.000000,195.000000,NaN,NaN

In [21]:
# Load and inspect the raw traffic data
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

TGMax2_SoFei_Ri1         34451
TGMax2_SoFei_Ri2         34451
Unnamed: 255             34451
Str_Zus                  34116
TGMax2_Sa_Ri1            29716
                         ...
DTV_Kfz_W_MobisFr_Q       4624
DTV_Kfz_W_MobisFr_Ri1     4624
bSo_Ri1                   4624
bSo_Ri2                   4624
bMo_Ri1                   4624
Length: 233, dtype: int64

In [22]:
# Load and inspect the raw traffic data
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [23]:
# Load and inspect the raw traffic data
df = df.drop_duplicates()

print(df.shape)

(34451, 256)

In [24]:
# Load and inspect the raw traffic data
df.replace(-1, np.nan, inplace=True)

,Jahr,TK_Nr,DZ_Nr,DZ_Name,Land_Nr,Land_Code,Str_Kl,Str_Nr,Str_Zus,Erf_Art,Fernziel_Ri1,Nahziel_Ri1,Hi_Ri1,Fernziel_Ri2,Nahziel_Ri2,Hi_Ri2,Anz_Fs_Q,Betriebs_km,vT_MobisSo,vT_W,vT_U,vT_S,DTV_Kfz_MobisSo_Q,DTV_Kfz_MobisSo_Ri1,DTV_Kfz_MobisSo_Ri2,DTV_Kfz_W_Q,DTV_Kfz_W_Ri1,DTV_Kfz_W_Ri2,DTV_Kfz_U_Q,DTV_Kfz_U_Ri1,DTV_Kfz_U_Ri2,DTV_Kfz_S_Q,DTV_Kfz_S_Ri1,DTV_Kfz_S_Ri2,Entw_Kfz_MobisSo_Q,Entw_Kfz_W_Q,Entw_Kfz_U_Q,Entw_Kfz_S_Q,DTV_SV_MobisSo_Q,DTV_SV_MobisSo_Ri1,DTV_SV_MobisSo_Ri2,DTV_SV_W_Q,DTV_SV_W_Ri1,DTV_SV_W_Ri2,DTV_SV_U_Q,DTV_SV_U_Ri1,DTV_SV_U_Ri2,DTV_SV_S_Q,DTV_SV_S_Ri1,DTV_SV_S_Ri2,Entw_SV_MobisSo_Q,Entw_SV_W_Q,Entw_SV_U_Q,Entw_SV_S_Q,pSV_MobisSo_Q,pSV_W_Q,pSV_U_Q,pSV_S_Q,fer,bSo,bFr,Mt,pMt,Mn,pMn,Md,pMd,Me,pMe,MSV30_Kfz_MobisSo_Q,MSV30_Kfz_W_Q,MSV30_Kfz_U_Q,MSV30_Kfz_S_Q,MSV30maxRi_Kfz_MobisSo,MSV30maxRi_Kfz_W,MSV30maxRi_Kfz_U,MSV30maxRi_Kfz_S,pMSV30maxRi_Kfz_MobisSo,pMSV30maxRi_Kfz_W,pMSV30maxRi_Kfz_U,pMSV30maxRi_Kfz_S,Ri_MSV30maxRi_Kfz_MobisSo,Ri_MSV30maxRi_Kfz_W,Ri_MSV30maxRi_Kfz_U,Ri_MSV30maxRi_Kfz_S,DL_Q,DL_Ri1,DL_Ri2,JG,WG_Ri1,WG_Ri2,TG_Mo_Ri1,TGMax1_Mo_Ri1,TGMax2_Mo_Ri1,TG_Mo_Ri2,TGMax1_Mo_Ri2,TGMax2_Mo_Ri2,TG_DiMiDo_Ri1,TGMax1_DiMiDo_Ri1,TGMax2_DiMiDo_Ri1,TG_DiMiDo_Ri2,TGMax1_DiMiDo_Ri2,TGMax2_DiMiDo_Ri2,TG_Fr_Ri1,TGMax1_Fr_Ri1,TGMax2_Fr_Ri1,TG_Fr_Ri2,TGMax1_Fr_Ri2,TGMax2_Fr_Ri2,TG_Sa_Ri1,TGMax1_Sa_Ri1,TGMax2_Sa_Ri1,TG_Sa_Ri2,TGMax1_Sa_Ri2,TGMax2_Sa_Ri2,TG_SoFei_Ri1,TGMax1_SoFei_Ri1,TGMax2_SoFei_Ri1,TG_SoFei_Ri2,TGMax1_SoFei_Ri2,TGMax2_SoFei_Ri2,pPLZ_MobisSo_Q,pLfw_MobisSo_Q,pMot_MobisSo_Q,pPmA_MobisSo_Q,pLoA_MobisSo_Q,pLzg_MobisSo_Q,pSat_MobisSo_Q,pBus_MobisSo_Q,pSon_MobisSo_Q,pPLZ_W_Q,pLfw_W_Q,pMot_W_Q,pPmA_W_Q,pLoA_W_Q,pLzg_W_Q,pSat_W_Q,pBus_W_Q,pSon_W_Q,pPLZ_U_Q,pLfw_U_Q,pMot_U_Q,pPmA_U_Q,pLoA_U_Q,pLzg_U_Q,pSat_U_Q,pBus_U_Q,pSon_U_Q,pPLZ_S_Q,pLfw_S_Q,pMot_S_Q,pPmA_S_Q,pLoA_S_Q,pLzg_S_Q,pSat_S_Q,pBus_S_Q,pSon_S_Q,Koor_UTM32_E,Koor_UTM32_N,DTV_Kfz_WU_MobisFr_Q,DTV_Kfz_WU_MobisFr_Ri1,DTV_Kfz_WU_MobisFr_Ri2,DTV_SV_WU_MobisFr_Q,DTV_SV_WU_MobisFr_Ri1,DTV_SV_WU_MobisFr_Ri2,DTV_Kfz_WU_Sa_Q,DTV_Kfz_WU_Sa_Ri1,DTV_Kfz_WU_Sa_Ri2,DTV_SV_WU_Sa_Q,DTV_SV_WU_Sa_Ri1,DTV_SV_WU_Sa_Ri2,MSV30_Kfz_MobisSo_Ri1,MSV30_Kfz_MobisSo_Ri2,MSV30_Kfz_W_Ri1,MSV30_Kfz_W_Ri2,MSV30_Kfz_U_Ri1,MSV30_Kfz_U_Ri2,MSV30_Kfz_S_Ri1,MSV30_Kfz_S_Ri2,bSV30_MobisSo_Ri1,bSV30_MobisSo_Ri2,bSV30_W_Ri1,bSV30_W_Ri2,bSV30_U_Ri1,bSV30_U_Ri2,bSV30_S_Ri1,bSV30_S_Ri2,DTV_Kfz_W_MobisFr_Q,DTV_Kfz_W_MobisFr_Ri1,DTV_Kfz_W_MobisFr_Ri2,DTV_SV_W_MobisFr_Q,DTV_SV_W_MobisFr_Ri1,DTV_SV_W_MobisFr_Ri2,pSV_W_MobisFr_Q,pSV_W_MobisFr_Ri1,pSV_W_MobisFr_Ri2,Koor_WGS84_N,Koor_WGS84_E,MSV50_Kfz_MobisSo_Ri1,MSV50_Kfz_MobisSo_Ri2,pMSV50_Kfz_MobisSo_Ri1,pMSV50_Kfz_MobisSo_Ri2,bSV50_MobisSo_Ri1,bSV50_MobisSo_Ri2,bLkwK50_MobisSo_Ri1,bLkwK50_MobisSo_Ri2,pMSV50_Kfz_W_MobisFr_Ri1,pMSV50_Kfz_W_MobisFr_Ri2,DTV_Kfz_NZB_DiMiDo_Ri1,DTV_Kfz_NZB_DiMiDo_Ri2,bSo_Ri1,bSo_Ri2,bMo_Ri1,bMo_Ri2,bFr_Ri1,bFr_Ri2,bSa_Ri1,bSa_Ri2,Q_P_D,Q_L1_D,Q_L2_D,Q_K_D,Q_P_E,Q_L1_E,Q_L2_E,Q_K_E,Q_P_N,Q_L1_N,Q_L2_N,Q_K_N,Geo_Sequ,Abschnitt_Ast,Station,Ausrichtung,Maut_SID_Ri1,Maut_SID_Ri2,Anz_Fs_Ri1,Anz_Fs_Ri2,DTA_SV_Ri1,fA_SV_Ri1,qBm_SV_Ri1,B_anno_SV_Ri1,DTA_SV_Ri2,fA_SV_Ri2,qBm_SV_Ri2,B_anno_SV_Ri2,DTV_Bus_Ri1,DTV_LoA_Ri1,DTV_Lzg_Ri1,DTV_Sat_Ri1,DTV_Bus_Ri2,DTV_LoA_Ri2,DTV_Lzg_Ri2,DTV_Sat_Ri2,Anmerkungen,Unnamed: 255
0,2023,2426,2218,AD HH-Südost (O),2,HH,A,1,NaN,2,Lübeck,AS Hamburg-Südost,N,Hamburg,AD Dreieck Hamburg-Südost (A25),S,6,"149,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,572.102,5.929.284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"53,50754848","10,08718293",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530,2426012O2426019O,"0,397",Ri1_ist_VonNK,2.533,1.034,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netzmodernisierung in 2023,NaN
1,2023,2426,2217,AD HH-Südost (W),2,HH,A,1,NaN,8+1,Lübeck,AD Dreieck Hamburg-Südost (A25),N,Hamburg,AK Kreuz Hamburg-Süd (A255),S,8,"150,3",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,569.966,5.929.459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"53,50941419","10,05502803",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520,2426019O2426001O,"0,477",Ri1_ist_VonNK,3.952,2.545,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Netzmodernisierung in 2023,NaN
2,2023,4908,5675,AK Leverkusen (O),5,NW,A,1,NaN,8+1,Dortmund,AS Burscheid,N,Köln,AK Kreuz Leverkusen (A3),S,6,"402,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.845,5.658.635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,06330659","7,07118583",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260,4908018A4908083A,"5,101",Ri1_ist_NachNK,2.374,907,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenprobleme in 2023,NaN
3,2023,4908,5035,AK Leverkusen (W),5,NW,A,1,NaN,8+1,Dortmund,AK Kreuz Leverkusen (A3),N,Köln,AK Kreuz Leverkusen-West (A59),S,6,"403,7",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358.801,5.655.933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,03757536","6,98603730",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250,4907071A4908018A,"1,613",Ri1_ist_NachNK,3.829,2.388,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Datenprobleme in 2023,NaN
4,2023,6507,353,AS Eppelborn,10,SL,A,1,NaN,8+1,Köln,AS Tholey,N,Saarbrücken,AS Eppelborn,S,5,"185,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,353.633,5.475.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"49,41525237","6,98198701",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,6507026O6507012O,"5,486",Ri1_ist_VonNK,278,2.197,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baustelle in 2023,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34446,2003,4414,5346,Ense-Möhnesee,5,NW,B,516,NaN,8+1,Brilon,"B229, Möhnesee",O,Werl,Bremen,W,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,433.970,5.706.383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"51,50472158","8,04863168",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neue Zählstelle,NaN
34447,2003,8413,8106,Bad Säckingen 3 Grenze,8,BW,B,518,NaN,8+1,Bad Säckingen,Bad Säckingen,N,Stein,Stein,S,2,"0,2",266.0,150.0,69.0,47.0,9.240,4.636,4.604,10.201,5.121,5.080,9.803,4.928,4.875,5.227,2.604,2.623,"+5,0","+4,5","+8,0","+4,0",478.000,198.0,280.0,607.000,250.0,357.0,491.000,207.0,283.0,17.0,9.0,8.0,"+8,8","+9,4","+9,9","-3,1","5,2","5,9","5,0","0,3","0,96","0,51","1,07",545.000,"5,3",66.0,"2,4",612.000,"6,1",344.000,"1,3",1.069,1.065,1.008,544.000,675.000,671.000,611.000,291.000,"14,6","13,1","12,4","11,1",R I,R I,R I,R II,D,E,D,A,A,A,F,18.0,NaN,B,7.0,NaN,F,18.0,NaN,B,7.0,NaN,F,17.0,NaN,B,7.0,NaN,F,11.0,NaN,F,12.0,NaN,C,15.0,NaN,C,17.0,NaN,"93,4","3,2","1,9","0,3","1,3","3,8","2,1","0,1","1,2","92,5","3,2","1,4","0,2","1,5","4,4","2,5","0,1","1,3","93,4","3,2","2,3","0,3","1,4","3,6","2,0","0,1","1,2","99,1","2,9","4,3","0,2","0,1","0,0","0,0","0,2","0,3",420.782,5.266.450,10.396,5.221,5.176,685.000,282.0,402.0,8.610,4.324,4.287,41.0,23.0,18.0,675.000,532.000,671.000,529.000,611.000,480.000,282.000,291.000,"4,4","4,1","4,0","2,6","5,7","0,6","0,0","0,0",10.478,5.258,5.220,707.000,290.00,417.0,"6,7","5,5","8,0","47,54663757","7,94721362",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.292,5.295,"0,50","0,51","0,94","0,94","1,08","1,07","0,83","0,82",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,277.977,277.978,1,1,783.000,"3,95","0,3",87.015,1.145,"4,09","0,31",129.185,4.0,57.0,137.0,80.0,3.0,66.0,210.0,117.0,NaN,NaN
34448,2003,5818,6310,Bad Vilbel,6,HE,B,521,NaN,2,Büdingen,Bad Vilbel,N,Frankfurt a. Main,AS Ffm.-Friedberger-Landstraße (A661),S,5,"552,0",334.0,203.0,71.0,60.0,32.255,17.199,15.055,35.240,18.830,16.410,31.779,16.978,14.801,22.186,11.649,10.537,"+0,8","+0,9","+1,1","-0,6",1.279,749.0,530.0,1.558,910.0,648.0,1.262,788.0,475.0,301.0,123.0,178.0,"-19,1","-17,3","-19,7","-39,6","4,0","4,4","4,0","1,4","0,90","0,65","1,03",1.825,"4,0",382.0,"3,3",1.904,"4,6",1.586,"2,1",2.738,2.730,2.648,2.038,1.818,1.813,1.756,1.053,"10,6","9,6","10,3","9,0",R I,R I,R I,R I,F,D,E,A,B,B,E,19.0,NaN,B,8.0,NaN,E,19.0,NaN,A,8.0,NaN,E,18.0,NaN,A,8.0,NaN,D,15.0,NaN,A,NaN,NaN,D,18.0,NaN,D,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480.686,5.556.939,35.881,19.183,16.699,1.651,988.0,663.0,26.754,14.244,12.510,646.0,343.0,304.0,1.818,1.788,1.813,1.785,1.756,1.620,1.053,1.006,"2,7","6,3","3,4","7,2","3,6","1,8","0,2","3,5",36.595,19.564,17.031,1.711,1.01,701.0,"4,7","5,2","4,1","50,16434712","8,72957982",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.672,17.218,"0,64","0,66","0,97","0,97","1,04","1,02","0,77","0,77",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34449,2003,8311,8910,Palmrainbrücke,8,BW,B,532,NaN,8+1,Weil am Rhein,Weil a. Rhein,O,Mülhausen (F),Bundesgrenze (F),W,2,"0,2",313.0,180.0,77.0,56.0,17.935,9.395,8.540,19.887,10.486,9.401,19.330,10.083,9.247,9.461,4.772,4.689,NaN,NaN,NaN,NaN,742.000,294.0,447.0,930.000,367.0,563.0,756.000,304.0,452.0,77.0,33.0,44.0,NaN,NaN,NaN,NaN,"4,1","4,7","3,9","0,8","0,97","0,46","1,06",1.029,"4,1",184.0,"4,2",1.134,"4,4",714.000,"2,7",1.863,1.852,1.781,988.000,1.438,1.437,1.317,514.000,"15,3","13,7","13,1","10,8",R I,R I,R I,R I,E,E,E,B,A,A,A,7.0,NaN,F,18.0,NaN,A,7.0,NaN,F,18.0,NaN,A,7.0,NaN,F,17.0,NaN,G,15.0,NaN,G,17.0,NaN,D,17.0,NaN,D,19.0,NaN,"94,9","3,0","1,8","0,4","1,4","2,7","1,9","0,1","0,5","94,4","3,0","1,6","0,4","1,5","3,1","2,1","0,1","0,5","95,1","3,0","2,3","0,5","1,4","2,5","1,7","0,1","0,5","98,4","2,7","2,7","0,5","0,3","0,4","0,2","0,2","0,2",394.476,5.272.933,20.500,10.847,9.653,1.015,400.0,615.0,15.998,8.077,7.920,235.0,102.0,134.0,1.438,1.189,1.437,1.186,1.317,1.122,514.000,509.000,"1,5","2,3","1,2","3,0","1,6","3,1","0,6","1,2",20.565,10.908,9.657,1.049,412.00,637.0,"5,1","3,8","6,6","47,60120836","7,59614946",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.998,9.755,"0,43","0,48","0,99","0,97","1,06","1,06","0,75","0,84",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,297.320,297.321,1,1,1.084,"3,68","0,29",116.153,1.785,"3,99","0,31",200.911,8.0,116.0,171.0,118.0,7.0,127.0,314.0,215.0,keine Daten 2002,NaN
34450,2003,7146,9420,Grafenau,9,BY,B,533,NaN,8+1,Grafenau,AS Roth,O,Schönberg,Rednitzhembach,W,3,"44,7",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,820.783,5.419.526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"48,84568129","13,37279482",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,266.508,303.066,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Load and inspect the raw traffic data
#AI recommendation: Check for missing values 
df.isnull().sum().sort_values(ascending=False)

TGMax2_SoFei_Ri2    34451
TGMax2_SoFei_Ri1    34451
Unnamed: 255        34451
Str_Zus             34116
TGMax2_Sa_Ri1       29716
                    ...
Koor_WGS84_E            0
Koor_WGS84_N            0
Anz_Fs_Ri1              0
Geo_Sequ                0
Anz_Fs_Ri2              0
Length: 256, dtype: int64

In [26]:
# Load and inspect the raw traffic data
if "Datum" in df.columns:

    df["Datum"] = pd.to_datetime(
        df["Datum"],
        errors="coerce"
    )

In [27]:
# Load and inspect the raw traffic data
if "Datum" in df.columns:

    df["Year"] = df["Datum"].dt.year

    df["Month"] = df["Datum"].dt.month

    df["Day"] = df["Datum"].dt.day

    df["Weekday"] = df["Datum"].dt.day_name()

    df["Quarter"] = df["Datum"].dt.quarter

In [28]:
# Load and inspect the raw traffic data
df.dtypes

Jahr              int64
TK_Nr             int64
DZ_Nr             int64
DZ_Name             str
Land_Nr           int64
                 ...
DTV_LoA_Ri2     float64
DTV_Lzg_Ri2     float64
DTV_Sat_Ri2     float64
Anmerkungen         str
Unnamed: 255    float64
Length: 256, dtype: object

In [29]:
# Load and inspect the raw traffic data
memory = df.memory_usage(deep=True).sum()

print(f"Memory Used : {memory/1024/1024:.2f} MB")

Memory Used : 241.71 MB

In [30]:
# Load and inspect the raw traffic data
road_columns = []

for c in df.columns:
    if "Str" in c or "Road" in c:
        road_columns.append(c)

In [31]:
# Replace "Strnum" with the correct road column if different
if "Strnum" in df.columns:
    print(df["Strnum"].unique())

In [32]:
# Load and inspect the raw traffic data
df.to_csv(
    "../data/cleaned_traffic.csv",
    index=False
)

print("Clean Dataset Saved Successfully")

Clean Dataset Saved Successfully

In [ ]:
# Load and inspect the raw traffic data
#AI helped in Summarisation
print("=" * 50)

print("DATA CLEANING SUMMARY")

print("=" * 50)

print(f"Rows : {df.shape[0]}")

print(f"Columns : {df.shape[1]}")

print(f"Missing Values : {df.isnull().sum().sum()}")

print(f"Duplicate Rows Removed : {duplicates}")

print("=" * 50)

==================================================
DATA CLEANING SUMMARY
==================================================
Rows : 34451
Columns : 256
Missing Values : 2540017
Duplicate Rows Removed : 0
==================================================

In [36]:
#German decimal separator is comma, so we need to replace it with a dot before converting to numeric
numeric_columns = [
    "Betriebs_km",
    "Koor_WGS84_N",
    "Koor_WGS84_E"
]

for col in numeric_columns:

    if col in df.columns:

        df[col] = (
            df[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
        )

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

In [37]:
#Convert year and road number columns to numeric if they exist
df["Jahr"] = pd.to_numeric(
    df["Jahr"],
    errors="coerce"
)

df["Str_Nr"] = pd.to_numeric(
    df["Str_Nr"],
    errors="coerce"
)

In [38]:
#Convert traffic volume columns to numeric
traffic_cols = [
    c for c in df.columns
    if c.startswith("DTV")
]

for col in traffic_cols:

    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", ".", regex=False)
    )

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [39]:
#Convert percentage columns to numeric
percentage_cols = [
    c for c in df.columns
    if c.startswith("p")
]

for col in percentage_cols:

    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", ".", regex=False)
    )

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [40]:
# Load and inspect the raw traffic data
print("=" * 60)
print("GERMAN AUTOBAHN TRAFFIC DATASET")
print("=" * 60)

print(f"Rows              : {len(df)}")
print(f"Columns           : {len(df.columns)}")
print(f"Years             : {df['Jahr'].nunique()}")
print(f"Roads             : {df['Str_Nr'].nunique()}")
print(f"Stations          : {df['DZ_Name'].nunique()}")
print(f"States            : {df['Land_Code'].nunique()}")

============================================================
GERMAN AUTOBAHN TRAFFIC DATASET
============================================================
Rows              : 34451
Columns           : 256
Years             : 21
Roads             : 323
Stations          : 2273
States            : 16

In [41]:
# Load and inspect the raw traffic data
print(sorted(df["Jahr"].unique()))

[np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023)]

In [43]:
#check unique road numbers or AUtobahn numbers
roads = sorted(df["Str_Nr"].unique())

print(roads)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(75), np.int64(76), np.int64(77), np.int64(79), np.int64(80), np.int64(81), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(106), np.int64(107), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(115), np.int64(122), np.int64(143), np.int64(158), np.int64(166), np.int64(167), np.int64(168), np.int64(169), np.int64(170), np.int64(171), np.int64(172), np.int64(173), np.int64(174), np.int64(175), np.int64(176), np.int64(178), np.int64(179), np.int64(180), np.int64(181), np.int64(183), np.int64(184), np.int64(185), np.int64(187), np.int64(188), np.int64(189), np.int64(190), np.int64(191), np.int64(192), np.int64(194), np.int64(195), np.int64(196), np.int64(197), np.int64(198), np.int64(199), np.int64(200), np.int64(202), np.int64(203), np.int64(206), np.int64(207), np.int64(208), np.int64(209), np.int64(210), np.int64(211), np.int64(212), np.int64(213), np.int64(214), np.int64(215), np.int64(216), np.int64(217), np.int64(219), np.int64(220), np.int64(221), np.int64(224), np.int64(226), np.int64(229), np.int64(230), np.int64(235), np.int64(236), np.int64(237), np.int64(239), np.int64(241), np.int64(242), np.int64(243), np.int64(244), np.int64(246), np.int64(247), np.int64(248), np.int64(249), np.int64(250), np.int64(252), np.int64(253), np.int64(254), np.int64(255), np.int64(256), np.int64(257), np.int64(258), np.int64(259), np.int64(260), np.int64(261), np.int64(262), np.int64(264), np.int64(265), np.int64(266), np.int64(267), np.int64(269), np.int64(270), np.int64(271), np.int64(275), np.int64(276), np.int64(279), np.int64(280), np.int64(281), np.int64(282), np.int64(285), np.int64(286), np.int64(288), np.int64(289), np.int64(290), np.int64(292), np.int64(293), np.int64(294), np.int64(299), np.int64(300), np.int64(301), np.int64(303), np.int64(304), np.int64(305), np.int64(311), np.int64(312), np.int64(317), np.int64(320), np.int64(321), np.int64(327), np.int64(352), np.int64(378), np.int64(388), np.int64(391), np.int64(392), np.int64(395), np.int64(401), np.int64(402), np.int64(403), np.int64(404), np.int64(406), np.int64(407), np.int64(408), np.int64(410), np.int64(416), np.int64(417), np.int64(419), np.int64(424), np.int64(427), np.int64(429), np.int64(430), np.int64(432), np.int64(433), np.int64(436), np.int64(437), np.int64(441), np.int64(442), np.int64(443), np.int64(444), np.int64(445), np.int64(446), np.int64(447), np.int64(448), np.int64(450), np.int64(454), np.int64(455), np.int64(456), np.int64(457), np.int64(459), np.int64(460), np.int64(462), np.int64(469), np.int64(470), np.int64(471), np.int64(472), np.int64(475), np.int64(477), np.int64(478), np.int64(480), np.int64(481), np.int64(483), np.int64(485), np.int64(486), np.int64(493), np.int64(496), np.int64(498), np.int64(500), np.int64(501), np.int64(502), np.int64(503), np.int64(504), np.int64(505), np.int64(506), np.int64(507), np.int64(511), np.int64(512), np.int64(514), np.int64(516), np.int64(518), np.int64(519), np.int64(521), np.int64(524), np.int64(525), np.int64(532), np.int64(533), np.int64(535), np.int64(544), np.int64(553), np.int64(555), np.int64(559), np.int64(560), np.int64(562), np.int64(565), np.int64(571), np.int64(573), np.int64(602), np.int64(620), np.int64(623), np.int64(643), np.int64(648), np.int64(650), np.int64(656), np.int64(659), np.int64(661), np.int64(671), np.int64(672), np.int64(861), np.int64(864), np.int64(952), np.int64(980), np.int64(995)]

In [44]:
# Load and inspect the raw traffic data
road_count = (
    df["Str_Nr"]
    .value_counts()
    .sort_index()
)

road_count.head(20)

Str_Nr
1     1079
2      936
3     1858
4      944
5      842
6     1177
7     1104
8     1213
9     1339
10     355
11     160
12     168
13     179
14     455
15     128
16      21
17      93
19     243
20     231
21      82
Name: count, dtype: int64

In [45]:
#check which stations have the most unique road numbers
stations = (
    df.groupby("Str_Nr")["DZ_Name"]
      .nunique()
      .sort_values(ascending=False)
)

stations.head(20)

Str_Nr
3     127
8      88
9      83
6      80
7      80
4      71
1      69
2      69
5      66
61     46
66     40
45     35
73     33
71     31
14     28
38     27
96     25
70     24
27     24
31     24
Name: DZ_Name, dtype: int64

In [46]:
# Load and inspect the raw traffic data
df.to_csv(
    "../data/cleaned_traffic.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [47]:
#count missing values for DtV columns
traffic_cols = [c for c in df.columns if c.startswith("DTV")]

missing = (
    df[traffic_cols]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing.head(20)

DTV_Sat_Ri2           8449
DTV_Sat_Ri1           8449
DTV_Bus_Ri2           6736
DTV_Lzg_Ri1           6736
DTV_Bus_Ri1           6736
DTV_LoA_Ri1           6736
DTV_Lzg_Ri2           6736
DTV_LoA_Ri2           6736
DTV_SV_S_Ri2          5366
DTV_SV_S_Ri1          5366
DTV_SV_S_Q            5366
DTV_SV_U_Ri2          5366
DTV_SV_W_Q            5366
DTV_SV_MobisSo_Ri2    5366
DTV_SV_MobisSo_Ri1    5366
DTV_SV_MobisSo_Q      5366
DTV_SV_W_Ri1          5366
DTV_SV_W_Ri2          5366
DTV_SV_U_Q            5366
DTV_SV_U_Ri1          5366
dtype: int64

In [48]:
#count available values for DTV columns
available = (
    df[traffic_cols]
    .notna()
    .sum()
    .sort_values(ascending=False)
)

available.head(20)

DTV_Kfz_MobisSo_Q         29827
DTV_Kfz_MobisSo_Ri1       29827
DTV_Kfz_MobisSo_Ri2       29827
DTV_Kfz_W_Q               29827
DTV_Kfz_W_Ri1             29827
DTV_Kfz_W_Ri2             29827
DTV_Kfz_U_Q               29827
DTV_Kfz_U_Ri1             29827
DTV_Kfz_U_Ri2             29827
DTV_Kfz_S_Q               29827
DTV_Kfz_S_Ri1             29827
DTV_Kfz_S_Ri2             29827
DTV_Kfz_W_MobisFr_Q       29827
DTV_Kfz_W_MobisFr_Ri1     29827
DTV_Kfz_WU_Sa_Ri2         29827
DTV_Kfz_WU_Sa_Q           29827
DTV_Kfz_WU_Sa_Ri1         29827
DTV_Kfz_WU_MobisFr_Q      29827
DTV_Kfz_WU_MobisFr_Ri2    29827
DTV_Kfz_WU_MobisFr_Ri1    29827
dtype: int64

In [49]:
# Load and inspect the raw traffic data
summary = pd.DataFrame({
    "Missing": df[traffic_cols].isna().sum(),
    "Available": df[traffic_cols].notna().sum()
})

summary = summary.sort_values(
    by="Available",
    ascending=False
)

summary.head(20)

                        Missing  Available
DTV_Kfz_MobisSo_Q          4624      29827
DTV_Kfz_MobisSo_Ri1        4624      29827
DTV_Kfz_MobisSo_Ri2        4624      29827
DTV_Kfz_W_Q                4624      29827
DTV_Kfz_W_Ri1              4624      29827
DTV_Kfz_W_Ri2              4624      29827
DTV_Kfz_U_Q                4624      29827
DTV_Kfz_U_Ri1              4624      29827
DTV_Kfz_U_Ri2              4624      29827
DTV_Kfz_S_Q                4624      29827
DTV_Kfz_S_Ri1              4624      29827
DTV_Kfz_S_Ri2              4624      29827
DTV_Kfz_W_MobisFr_Q        4624      29827
DTV_Kfz_W_MobisFr_Ri1      4624      29827
DTV_Kfz_WU_Sa_Ri2          4624      29827
DTV_Kfz_WU_Sa_Q            4624      29827
DTV_Kfz_WU_Sa_Ri1          4624      29827
DTV_Kfz_WU_MobisFr_Q       4624      29827
DTV_Kfz_WU_MobisFr_Ri2     4624      29827
DTV_Kfz_WU_MobisFr_Ri1     4624      29827

In [50]:
# Load and inspect the raw traffic data
summary.head(30)

                     Missing  Available
DTV_Kfz_MobisSo_Q       4624      29827
DTV_Kfz_MobisSo_Ri1     4624      29827
DTV_Kfz_MobisSo_Ri2     4624      29827
DTV_Kfz_W_Q             4624      29827
DTV_Kfz_W_Ri1           4624      29827
...                      ...        ...
DTV_SV_MobisSo_Ri2      5366      29085
DTV_SV_MobisSo_Ri1      5366      29085
DTV_SV_MobisSo_Q        5366      29085
DTV_SV_U_Ri1            5366      29085
DTV_SV_U_Q              5366      29085

[30 rows x 2 columns]

In [51]:
# Load and inspect the raw traffic data
complete = df.dropna(
    subset=traffic_cols,
    how="all"
)

complete.head()

,Jahr,TK_Nr,DZ_Nr,DZ_Name,Land_Nr,Land_Code,Str_Kl,Str_Nr,Str_Zus,Erf_Art,Fernziel_Ri1,Nahziel_Ri1,Hi_Ri1,Fernziel_Ri2,Nahziel_Ri2,Hi_Ri2,Anz_Fs_Q,Betriebs_km,vT_MobisSo,vT_W,vT_U,vT_S,DTV_Kfz_MobisSo_Q,DTV_Kfz_MobisSo_Ri1,DTV_Kfz_MobisSo_Ri2,DTV_Kfz_W_Q,DTV_Kfz_W_Ri1,DTV_Kfz_W_Ri2,DTV_Kfz_U_Q,DTV_Kfz_U_Ri1,DTV_Kfz_U_Ri2,DTV_Kfz_S_Q,DTV_Kfz_S_Ri1,DTV_Kfz_S_Ri2,Entw_Kfz_MobisSo_Q,Entw_Kfz_W_Q,Entw_Kfz_U_Q,Entw_Kfz_S_Q,DTV_SV_MobisSo_Q,DTV_SV_MobisSo_Ri1,DTV_SV_MobisSo_Ri2,DTV_SV_W_Q,DTV_SV_W_Ri1,DTV_SV_W_Ri2,DTV_SV_U_Q,DTV_SV_U_Ri1,DTV_SV_U_Ri2,DTV_SV_S_Q,DTV_SV_S_Ri1,DTV_SV_S_Ri2,Entw_SV_MobisSo_Q,Entw_SV_W_Q,Entw_SV_U_Q,Entw_SV_S_Q,pSV_MobisSo_Q,pSV_W_Q,pSV_U_Q,pSV_S_Q,fer,bSo,bFr,Mt,pMt,Mn,pMn,Md,pMd,Me,pMe,MSV30_Kfz_MobisSo_Q,MSV30_Kfz_W_Q,MSV30_Kfz_U_Q,MSV30_Kfz_S_Q,MSV30maxRi_Kfz_MobisSo,MSV30maxRi_Kfz_W,MSV30maxRi_Kfz_U,MSV30maxRi_Kfz_S,pMSV30maxRi_Kfz_MobisSo,pMSV30maxRi_Kfz_W,pMSV30maxRi_Kfz_U,pMSV30maxRi_Kfz_S,Ri_MSV30maxRi_Kfz_MobisSo,Ri_MSV30maxRi_Kfz_W,Ri_MSV30maxRi_Kfz_U,Ri_MSV30maxRi_Kfz_S,DL_Q,DL_Ri1,DL_Ri2,JG,WG_Ri1,WG_Ri2,TG_Mo_Ri1,TGMax1_Mo_Ri1,TGMax2_Mo_Ri1,TG_Mo_Ri2,TGMax1_Mo_Ri2,TGMax2_Mo_Ri2,TG_DiMiDo_Ri1,TGMax1_DiMiDo_Ri1,TGMax2_DiMiDo_Ri1,TG_DiMiDo_Ri2,TGMax1_DiMiDo_Ri2,TGMax2_DiMiDo_Ri2,TG_Fr_Ri1,TGMax1_Fr_Ri1,TGMax2_Fr_Ri1,TG_Fr_Ri2,TGMax1_Fr_Ri2,TGMax2_Fr_Ri2,TG_Sa_Ri1,TGMax1_Sa_Ri1,TGMax2_Sa_Ri1,TG_Sa_Ri2,TGMax1_Sa_Ri2,TGMax2_Sa_Ri2,TG_SoFei_Ri1,TGMax1_SoFei_Ri1,TGMax2_SoFei_Ri1,TG_SoFei_Ri2,TGMax1_SoFei_Ri2,TGMax2_SoFei_Ri2,pPLZ_MobisSo_Q,pLfw_MobisSo_Q,pMot_MobisSo_Q,pPmA_MobisSo_Q,pLoA_MobisSo_Q,pLzg_MobisSo_Q,pSat_MobisSo_Q,pBus_MobisSo_Q,pSon_MobisSo_Q,pPLZ_W_Q,pLfw_W_Q,pMot_W_Q,pPmA_W_Q,pLoA_W_Q,pLzg_W_Q,pSat_W_Q,pBus_W_Q,pSon_W_Q,pPLZ_U_Q,pLfw_U_Q,pMot_U_Q,pPmA_U_Q,pLoA_U_Q,pLzg_U_Q,pSat_U_Q,pBus_U_Q,pSon_U_Q,pPLZ_S_Q,pLfw_S_Q,pMot_S_Q,pPmA_S_Q,pLoA_S_Q,pLzg_S_Q,pSat_S_Q,pBus_S_Q,pSon_S_Q,Koor_UTM32_E,Koor_UTM32_N,DTV_Kfz_WU_MobisFr_Q,DTV_Kfz_WU_MobisFr_Ri1,DTV_Kfz_WU_MobisFr_Ri2,DTV_SV_WU_MobisFr_Q,DTV_SV_WU_MobisFr_Ri1,DTV_SV_WU_MobisFr_Ri2,DTV_Kfz_WU_Sa_Q,DTV_Kfz_WU_Sa_Ri1,DTV_Kfz_WU_Sa_Ri2,DTV_SV_WU_Sa_Q,DTV_SV_WU_Sa_Ri1,DTV_SV_WU_Sa_Ri2,MSV30_Kfz_MobisSo_Ri1,MSV30_Kfz_MobisSo_Ri2,MSV30_Kfz_W_Ri1,MSV30_Kfz_W_Ri2,MSV30_Kfz_U_Ri1,MSV30_Kfz_U_Ri2,MSV30_Kfz_S_Ri1,MSV30_Kfz_S_Ri2,bSV30_MobisSo_Ri1,bSV30_MobisSo_Ri2,bSV30_W_Ri1,bSV30_W_Ri2,bSV30_U_Ri1,bSV30_U_Ri2,bSV30_S_Ri1,bSV30_S_Ri2,DTV_Kfz_W_MobisFr_Q,DTV_Kfz_W_MobisFr_Ri1,DTV_Kfz_W_MobisFr_Ri2,DTV_SV_W_MobisFr_Q,DTV_SV_W_MobisFr_Ri1,DTV_SV_W_MobisFr_Ri2,pSV_W_MobisFr_Q,pSV_W_MobisFr_Ri1,pSV_W_MobisFr_Ri2,Koor_WGS84_N,Koor_WGS84_E,MSV50_Kfz_MobisSo_Ri1,MSV50_Kfz_MobisSo_Ri2,pMSV50_Kfz_MobisSo_Ri1,pMSV50_Kfz_MobisSo_Ri2,bSV50_MobisSo_Ri1,bSV50_MobisSo_Ri2,bLkwK50_MobisSo_Ri1,bLkwK50_MobisSo_Ri2,pMSV50_Kfz_W_MobisFr_Ri1,pMSV50_Kfz_W_MobisFr_Ri2,DTV_Kfz_NZB_DiMiDo_Ri1,DTV_Kfz_NZB_DiMiDo_Ri2,bSo_Ri1,bSo_Ri2,bMo_Ri1,bMo_Ri2,bFr_Ri1,bFr_Ri2,bSa_Ri1,bSa_Ri2,Q_P_D,Q_L1_D,Q_L2_D,Q_K_D,Q_P_E,Q_L1_E,Q_L2_E,Q_K_E,Q_P_N,Q_L1_N,Q_L2_N,Q_K_N,Geo_Sequ,Abschnitt_Ast,Station,Ausrichtung,Maut_SID_Ri1,Maut_SID_Ri2,Anz_Fs_Ri1,Anz_Fs_Ri2,DTA_SV_Ri1,fA_SV_Ri1,qBm_SV_Ri1,B_anno_SV_Ri1,DTA_SV_Ri2,fA_SV_Ri2,qBm_SV_Ri2,B_anno_SV_Ri2,DTV_Bus_Ri1,DTV_LoA_Ri1,DTV_Lzg_Ri1,DTV_Sat_Ri1,DTV_Bus_Ri2,DTV_LoA_Ri2,DTV_Lzg_Ri2,DTV_Sat_Ri2,Anmerkungen,Unnamed: 255
8,2023,2427,1102,Barsbüttel,1,SH,A,1,NaN,8+1,Lübeck,AS Barsbüttel,N,Hamburg,AK Kreuz Hamburg-Ost (A24),S,7,7.5,350.0,214.0,77.0,59.0,87.412,44.896,42.516,90.174,46.941,43.234,91.175,47.090,44.085,72.652,34.715,37.937,"+0,4","+1,1","-0,5","-0,7",11.883,6.454,5.429,14.431,7.832,6.598,12.211,6.673,5.538,2.227,1.177,1.051,"-4,9","-4,5","-4,7","-3,7",13.6,16.0,13.4,3.1,"1,01","0,80","1,04",4.928,12.2,1.07,26.7,5.440,12.9,3.392,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,D,B,D,E,17.0,NaN,G,8.0,NaN,E,17.0,NaN,B,8.0,NaN,E,16.0,NaN,C,NaN,NaN,C,11.0,13.0,D,12.0,NaN,B,12.0,NaN,B,13.0,NaN,82.5,9.9,0.3,1.4,2.8,10.5,9.0,0.3,2.5,80.3,10.5,0.3,1.2,3.3,12.4,10.7,0.3,2.5,82.4,10.0,0.3,1.6,2.7,10.4,8.9,0.3,2.6,92.6,6.9,0.4,1.7,0.7,2.1,1.9,0.3,2.6,578.185,5.935.581,92.739,48.117,44.622,15.491,8.339,7.152,79.295,41.486,37.808,5.983,3.646,2.337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.435,48.085,44.350,15.849,8.535,7.314,17.1,17.7,16.5,53.563276,10.180465,4.252,3.957,9.5,9.3,"8,0","11,1","6,3","8,7",8.8,8.9,49.147,46.057,"0,72","0,87","0,94","0,97","1,07","1,01","0,82","0,84",4.723,171.0,529.0,18.0,3.080,52.0,249.0,11.0,782.0,53.0,233.0,2.0,560,2426101O2427132O,"1,330",Ri1_ist_NachNK,5.756,5.759,3,4,26.853,"4,16","0,32",2.841.555,23.262,"4,28","0,33",2.391.188,88.0,1.502,4.864,4.204,164.0,927.0,4.339,3.683,NaN,NaN
9,2023,6307,173,Bierfeld,10,SL,A,1,NaN,8+1,Köln,AS Nonnweiler-Bierfeld,N,Saarbrücken,AD Dreieck Nonnweiler (A62),S,4,160.6,324.0,205.0,64.0,55.0,24.739,12.462,12.277,25.202,12.708,12.494,25.455,12.985,12.470,22.246,10.957,11.288,"+4,0","+5,2","+0,6","+4,6",3.700,1.894,1.806,4.542,2.338,2.204,3.845,1.965,1.880,612.000,274.000,338.000,"-2,2","-1,2","-3,0","-3,1",15.0,18.0,15.1,2.8,"1,01","0,86","1,13",1.420,13.9,253.00,27.0,1.579,14.8,941.000,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,C,D,C,D,B,8.0,NaN,D,9.0,16.0,D,8.0,17.0,E,17.0,NaN,E,16.0,NaN,E,16.0,NaN,C,11.0,13.0,D,12.0,NaN,B,12.0,NaN,C,16.0,NaN,82.0,8.9,0.9,1.5,3.7,11.0,8.5,0.3,1.5,79.1,9.5,0.9,1.3,4.2,13.5,10.4,0.3,1.6,81.7,9.2,0.9,1.6,3.8,11.0,8.6,0.2,1.6,94.2,6.5,1.1,1.8,1.4,1.1,0.8,0.2,1.3,352.990,5.496.258,25.877,13.099,12.778,4.989,2.569,2.420,22.358,11.262,11.096,1.329,659.000,670.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.811,13.028,12.783,5.106,2.633,2.473,19.8,20.2,19.3,49.601001,6.965425,1.301,1.271,10.4,10.4,"9,5","8,6","6,3","5,9",10.0,9.9,13.074,12.790,"0,82","0,90","0,97","0,99","1,15","1,12","0,83","0,83",1.331,66.0,167.0,15.0,845.000,20.0,68.0,8.0,183.0,13.0,55.0,2.0,120,6307405O6407086O,"0,752",Ri1_ist_VonNK,6.096,6.095,2,2,7.756,"4,09","0,32",897.627,7.391,"4,09","0,32",855.829,31.0,473.000,1.390,1.095,37.0,441.0,1.327,1.009,NaN,NaN
11,2023,2821,3302,Bockel,3,NI,A,1,NaN,8+1,Hamburg,AS Bockel,N,Bremen,AS Stuckenborstel,S,6,72.2,265.0,164.0,64.0,37.0,69.465,34.610,34.856,68.452,34.135,34.318,73.354,36.886,36.467,67.775,33.203,34.572,"+4,4","+4,8","+3,6","+4,1",13.923,6.898,7.024,16.912,8.356,8.555,14.489,7.207,7.282,2.598,1.331,1.267,"-3,9","-3,5","-3,3","+1,9",20.0,24.7,19.8,3.8,"1,07","0,97","1,14",3.880,17.3,924.00,42.8,4.235,17.7,2.813,15.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,C,E,D,D,C,NaN,NaN,C,NaN,NaN,C,NaN,NaN,C,NaN,NaN,E,17.0,NaN,E,13.0,NaN,F,13.0,NaN,F,12.0,NaN,C,15.0,NaN,C,13.0,NaN,77.9,10.9,0.2,1.9,1.8,18.1,15.4,0.2,0.1,73.4,11.3,0.2,1.7,2.1,22.4,19.1,0.2,0.2,77.9,11.1,0.2,2.2,1.8,17.7,15.2,0.2,0.1,93.9,9.3,0.3,2.2,0.5,3.0,2.7,0.3,0.1,518.757,5.893.524,70.292,35.056,35.236,18.230,8.961,9.269,67.488,34.132,33.357,6.634,3.583,3.051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.250,34.492,34.758,18.634,9.157,9.478,26.9,26.5,27.3,53.190718,9.280734,3.683,3.812,10.6,10.9,"4,1","2,1","3,3","1,2",10.7,11.0,34.539,34.610,"0,93","1,01","0,97","0,97","1,13","1,15","0,90","0,96",3.476,84.0,666.0,9.0,2.369,38.0,401.0,5.0,528.0,27.0,368.0,1.0,450,2821001O2821002O,"0,059",Ri1_ist_NachNK,1.786,334,3,3,31.397,"4,55","0,34",3.502.889,31.878,"4,54","0,34",3.551.607,82.0,584.000,6.232,5.309,82.0,634.0,6.308,5.402,NaN,NaN
12,2023,2625,3444,Dibbersen,3,NI,A,1,NaN,8+1,Hamburg,AS Hittfeld,N,Bremen,AS Dibbersen,S,4,20.5,204.0,129.0,49.0,26.0,61.838,30.731,31.108,63.606,31.932,31.674,63.864,31.713,32.152,52.850,25.157,27.693,"+2,9","+3,1","+3,3","+2,1",9.913,4.931,4.983,11.915,5.955,5.959,10.426,5.151,5.276,2.149,1.013,1.136,"+0,6","+0,3","+2,0","+17,5",16.0,18.7,16.3,4.1,"1,00","0,86","1,08",3.478,14.1,773.00,33.3,3.831,14.7,2.420,11.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,D,B,D,G,8.0,NaN,E,17.0,NaN,B,8.0,NaN,E,17.0,NaN,C,NaN,NaN,E,15.0,NaN,D,13.0,NaN,D,13.0,NaN,C,15.0,NaN,B,13.0,NaN,82.2,10.6,0.2,1.7,2.8,13.0,10.9,0.3,0.1,79.6,11.2,0.2,1.5,3.2,15.3,12.9,0.3,0.1,81.7,10.6,0.2,1.9,3.0,13.1,11.1,0.2,0.1,93.8,8.0,0.4,2.0,1.1,2.6,2.4,0.3,0.1,564.261,5.914.886,65.412,32.790,32.622,12.893,6.384,6.509,55.306,27.438,27.868,4.788,2.584,2.204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.242,32.814,32.428,13.120,6.529,6.591,20.1,19.9,20.3,53.379166,9.966033,2.739,2.910,8.9,9.4,"7,5","13,0","5,2","10,2",8.3,9.0,32.756,32.913,"0,80","0,91","0,95","0,96","1,10","1,06","0,87","0,90",3.260,122.0,440.0,9.0,2.137,47.0,230.0,6.0,515.0,31.0,227.0,1.0,460,2625001O2625002O,"5,624",Ri1_ist_NachNK,955,1.859,2,2,21.232,"4,31","0,33",2.551.897,21.403,"4,3","0,33",2.566.489,81.0,855.000,3.995,3.371,76.0,890.0,4.017,3.391,NaN,NaN
13,2023,5206,5060,Euskirchen/Bliesheim,5,NW,A,1,NaN,8+1,Köln,AK Kreuz Bliesheim (A61/A553),N,Saarbrücken,AS Euskirchen (L264),S,4,443.1,300.0,183.0,75.0,42.0,52.079,26.190,25.889,53.635,26.647,26.989,53.358,26.645,26.712,44.965,24.005,20.960,"+9,2","+8,9","+10,2","+10,0",5.499,2.826,2.673,6.615,3.365,3.250,5.793,2.983,2.810,1.166,715.000,451.000,"+1,4","+1,8","+1,3","+11,2",10.6,12.3,10.9,2.6,"0,99","0,83","1,08",2.963,9.7,584.00,19.2,3.278,10.4,2.017,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,C,B,D,B,B,8.0,NaN,E,17.0,NaN,B,8.0,NaN,E,17.0,NaN,B,8.0,NaN,E,16.0,NaN,A,NaN,NaN,D,13.0,NaN,D,19.0,NaN,B,13.0,NaN,87.8,9.9,0.5,1.6,2.5,7.9,6.7,0.1,0.0,86.1,10.5,0.4,1.5,2.9,9.3,7.9,0.1,0.0,87.2,10.1,0.5,1.9,2.6,8.2,6.9,0.1,0.0,95.7,7.0,1.0,1.7,0.9,1.7,1.4,0.1,0.0,346.069,5.625.358,54.785,27.261,27.524,7.248,3.683,3.565,47.690,23.690,24.000,2.339,1.264,1.075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.839,27.231,27.608,7.372,3.736,3.636,13.4,13.7,13.2,50.759552,6.817452,2.771,2.940,10.6,11.4,"7,6","6,4","5,6","4,5",10.2,10.6,27.947,27.813,"0,89","0,77","0,96","0,96","1,05","1,12","0,84","0,84",2.919,93.0,248.0,18.0,1.882,27.0,99.0,9.0,471.0,18.0,94.0,1.0,170,5206054O5206045X,"0,910",Ri1_ist_NachNK,6.365,6.364,2,2,11.740,"4,15","0,32",1.371.411,11.064,"4,14","0,32",1.291.838,25.0,669.000,2.131,1.786,26.0,650.0,1.997,1.706,NaN,NaN